# Generated by Django 3.2.5 on 2021-07-21 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions_bid_category_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchItem', to='auctions.auctions')),
                ('watch_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userWatch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
