# Generated by Django 3.2.5 on 2021-07-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210721_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
