# Generated by Django 3.2.5 on 2021-09-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctions_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='product',
            field=models.URLField(default='https://pngtree.com/freepng/no-image-vector-illustration-isolated_4979075.html', max_length=600),
        ),
    ]
