# Generated by Django 3.2.5 on 2021-09-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctions_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='product',
            field=models.URLField(default='https://png.pngtree.com/png-clipart/20190925/original/pngtree-no-image-vector-illustration-isolated-png-image_4979075.jpg', max_length=600),
        ),
    ]
