# Generated by Django 3.2.5 on 2021-10-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20211013_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product_category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Toys', 'Toys'), ('Men', 'Men'), ('Women', 'Women'), ('Children', 'Children'), ('Shoes', 'Shoes'), ('Furniture', 'Furniture'), ('Clothing', 'Clothing'), ('Hair', 'Hair'), ('Watches', 'Watches')], max_length=30, unique=True),
        ),
    ]
